// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaWO80aG0y__DYMQPb5q5pl2hh9m0EDGo',
    appId: '1:110139743599:web:e648b33ae6cc52e8eadc9a',
    messagingSenderId: '110139743599',
    projectId: 'superexpress-1afc7',
    authDomain: 'superexpress-1afc7.firebaseapp.com',
    storageBucket: 'superexpress-1afc7.appspot.com',
    measurementId: 'G-P76FX2LZ3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeCKBHwRulhivWfWmG0xouMRPOarHLPVo',
    appId: '1:110139743599:android:cd5f8850e9ee04dbeadc9a',
    messagingSenderId: '110139743599',
    projectId: 'superexpress-1afc7',
    storageBucket: 'superexpress-1afc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2As6MTZSe7f3D8dQJ6R-pkqLHHxL3pzo',
    appId: '1:110139743599:ios:3459b576375c94f6eadc9a',
    messagingSenderId: '110139743599',
    projectId: 'superexpress-1afc7',
    storageBucket: 'superexpress-1afc7.appspot.com',
    iosBundleId: 'com.example.superexpressTcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2As6MTZSe7f3D8dQJ6R-pkqLHHxL3pzo',
    appId: '1:110139743599:ios:4e4985f7a68599e7eadc9a',
    messagingSenderId: '110139743599',
    projectId: 'superexpress-1afc7',
    storageBucket: 'superexpress-1afc7.appspot.com',
    iosBundleId: 'com.example.superexpressTcc.RunnerTests',
  );
}
